### PR TITLE
Feature/remove-unneeded-steps

### PR DESCRIPTION
**Pull request by cjfullerton**
Some minor cleanup:
- Removes version check from build workflow
- Removes upload of spec file and build dir from release workflow
- Fixes an error in README (git fetch command was incorrect)

Caveat: Have not tested release workflow.

### CODE REVIEW

**Review by aplowman — CHANGES_REQUESTED** [review]
We also need to remove spec/build upload from the `build-executables-linux` job in the release workflow. (This has to be a separate job because it must run on a CentOS docker image, rather than the standard Ubuntu GitHub runner.)

**Review by aplowman — CHANGES_REQUESTED** [review]
And the version check step from the `build-executables-linux` job in the build workflow! 😄

**Comment by cjfullerton** [comment]
Haha. 🤦

**Review by aplowman — APPROVED** [review]

**Comment by cjfullerton** [comment]
😌 

Will add these to hpcflow and matflow later today.

**Comment by aplowman** [comment]
Cheers!

**Pull request merged**
